spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://185.233.187.153:5432/default_db
    username: gen_user
    password: 3sNCIzHQTwKxl

  thymeleaf:
    check-template-location: false
server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
